Admin inventory functionality
greyhixson/tech-center-checkout pull request #104
Opened 2022-03-20 21:48 UTC by kendra-r

This is one is kinda a doozy...so I'll try my best to give a good overview of what I changed. Also, please don't work on this over Spring Break!! :)

Task 1: Add Validation when editing devices in AllDevices 
Validation Added in save() function (called when user clicks the SAVE button): 
- If any field is blank, then a message saying "Please don't leave any field blank." is displayed on the screen. 
- If the Device Tag field contains anything other than a number, then a message saying "Device Tag should contain numbers only." is displayed on the screen. 
- If the user attempts to use a pre-existing device tag when editing or adding a device, then a message saying "Device Tag is already taken." is displayed on the screen. 

Task 2: When items are added or deleted, commit them to the database in AllDevices 

- Async functions added to techCenterCheckout.Data.js: deleteDevice, updateDevice, and addDevice. They respectively delete items, update existing items, and add new items to the All Devices table in the database. 

Task 3: Update the AdminView to reflect fewer components 

- Currently only three cards on Admin Dashboard: Active Reservations, Reservation Log, and Inventory
- Got rid of the hover effect...user can click directly on the cards and it will link them to the appropriate page 
- The Reservation Log card currently has no link because the reservation log itself has not yet been implemented

2022-03-26 23:02 UTC, greyhixson requested changes
Good job on the rework. This is a big task, so I have several comments.

- Lots of console logs and commented out code that shouldn't be there
- Eslint warnings shouldn't be ignored by disabling them. That would be like breaking your smoke alarm because it started beeping. Figure out what they're telling you and fix it.
- The firebase functions for committing edited items wasn't working for me.

2022-03-26 23:02 UTC, greyhixson commented on src/components/Admin/AllDevices.vue
> +          align="center"
align="center" is obsolete and doesn't exist on v-data-tables
```suggestion

```

2022-03-26 23:02 UTC, greyhixson commented on src/components/Admin/AllDevices.vue
> +                              style="color=black;"
style="color=black;" should be style="color:black;", it's redundant with color="black" so it should be deleted regardless. I also don't see a difference with color="black" and without it so I'd delete it unless you can see a difference.

2022-03-26 23:02 UTC, greyhixson commented on src/components/Admin/AllDevices.vue
> +                          /> -->
```suggestion
```

2022-03-26 23:02 UTC, greyhixson commented on src/components/Admin/AllDevices.vue
> +import { addDevice } from '../../firebase/techCenterCheckout.Data';
If you see an eslint warning, it's probably because you're doing something the wrong way. Don't just hide the warnings, figure out why it's telling you them. Why go to a grocery store four times for four items when you can get all four from one visit? 
```suggestion
import {
  getCollection, deleteDevice, updateDevice, addDevice,
} from '@/firebase/techCenterCheckout.Data';
```

2022-03-26 23:02 UTC, greyhixson commented on src/components/Admin/AllDevices.vue
> +      // y.style.display = 'none';
console logs shouldn't exist, and neither should commented out code

2022-03-26 23:02 UTC, greyhixson commented on src/components/Admin/AllDevices.vue
>      // need async add & delete to FB collection
It looks like you did just that. Remove comment if so.

2022-03-26 23:02 UTC, greyhixson commented on src/components/Admin/AllDevices.vue
> +      }
You know the drill

2022-03-29 18:00 UTC, greyhixson requested changes
Closer, still missing a couple comments and I'm not sure why you prefer 'document' over 'doc' I find doc to be more readable. Also, when I edit an item, the request still fails.

2022-03-29 18:00 UTC, greyhixson commented on src/components/User/UserRes.vue
> +      // console.log(itemToDelete);
```suggestion
```

2022-03-29 18:00 UTC, greyhixson commented on src/components/User/UserRes.vue
> +        // console.log(deleted);
```suggestion
```

2022-03-29 18:00 UTC, greyhixson commented on src/firebase/techCenterCheckout.Data.js
> +/* eslint-disable prefer-destructuring */
mine built without this line, but you can leave it if yours doesn't

2022-03-31 16:41 UTC, greyhixson requested changes
Visual bug
![image](https://user-images.githubusercontent.com/27748673/161106782-b188196e-3380-4ed2-93bc-591142d72c72.png)

2022-04-02 09:11 UTC, kendra-r commented on src/firebase/techCenterCheckout.Data.js
> +/* eslint-disable prefer-destructuring */
Unfortunately, mine didn't build without this line, so I'm going to have to keep it in.

2022-04-02 09:40 UTC, kendra-r reviewed
All changes look good. I addressed the visual bug with editing an item as well. The ability to edit a device tag for a pre-existing time is now disabled.

2022-04-02 22:32 UTC, greyhixson approved these changes
Good job!

2022-04-02 22:33 UTC, merged