Add FB functionality to UserHome, Created new FB function
greyhixson/tech-center-checkout pull request #85
Opened 2022-03-09 17:35 UTC by plstarkey18

For this pull request, I added FB functionality to the UserHome page, which is now in a datatable format compared to the expansion panels. I decided to create a new function that requested deviceName, deviceTag, and min and max duration that can be displayed for the user. I have a plan that once the user clicks the reserve button, then it will grab the deviceTag and query the availability in the review reservation page. I created a function to make sure that once the button is clicked, it will log in the console the right item. I also made minor changes to the ReviewRes component, but it is only design and not functionality.

2022-03-11 15:10 UTC, greyhixson requested changes
Looks good except for the console.log. Similarly to everyone elses right now we have a bunch of v-data-tables that all look the same. Next sprint everyone will need to style them, so they are dissimilar and friendlier to use.

2022-03-11 15:10 UTC, greyhixson commented on src/components/User/UserHome.vue
> +      console.log(this.selectedItem.deviceName);
```suggestion
      
```

2022-03-12 03:10 UTC, plstarkey18 commented
After I fixed your requested changes, I updated my branch to reflect Brian's merge with master. Should be up to date now.

2022-03-13 17:11 UTC, greyhixson approved these changes
Great job!

2022-03-13 17:11 UTC, merged