Admin Res Data Pull From FB
greyhixson/tech-center-checkout pull request #90
Opened 2022-03-13 04:08 UTC by dperezd

Files edited: AdminActive.vue, AdminLog.vue, and techCenterCheckoutData.js

Upcoming Reservations and Reservations Log table now pull data from firebase.
-created two new functions in techCenterCheckoutData.js (getAdminCurrent, getResLog)
-created new method in AdminActive.vue and AdminLog.vue

2022-03-13 17:14 UTC, greyhixson requested changes
Code looks good, but the date isn't being displayed properly:
![image](https://user-images.githubusercontent.com/27748673/158071084-0f340362-7f87-4c28-9905-e8fcc8b73d51.png)

2022-03-13 23:05 UTC, dperezd commented
I changed timestamp error in techCenterCheckout.Data.js

2022-03-14 03:59 UTC, greyhixson requested changes
Better but what's the '3991', and it's wordy to say Central Daylight Time or Central Standard Time. A lot of extra detail is in the date that should be hidden.
![image](https://user-images.githubusercontent.com/27748673/158102569-9468cdfa-9ff0-4e4f-8242-40822ca477d3.png)

2022-03-26 19:50 UTC, dperezd commented
I changed the data table in both pages to lists (Tables didn't feel necessary since admin will most likely not be modifying these). I have still not been able to resolve the date display issue, I haven't found a good way to transition from timestamps to dates to strings. I am still working out of this same branch.

2022-03-26 23:10 UTC, greyhixson requested changes
Out of date with master and a small spacing thing. Besides that good job!

2022-03-26 23:10 UTC, greyhixson commented on src/components/Admin/AdminLog.vue
> +
lots of unnecessary spacing
```suggestion
          <v-list-item-subtitle v-text="'Reservation ID: ' + device.reservationID" />
          <v-list-item-subtitle v-text="'Device Tag: ' + device.deviceTag" />
          <v-list-item-subtitle v-text="'Username: ' + device.username" />
          <v-list-item-subtitle v-text="'First Name: ' + device.firstName" />
          <v-list-item-subtitle v-text="'Last Name: ' + device.lastName" />
```

2022-03-29 16:54 UTC, greyhixson approved these changes

2022-03-29 16:55 UTC, merged